### ISSUE TITLE
Datepicker jquery

### ISSUE THREAD

**Issue by bellisa03** [bellisa03/tophit#1]
Hello Michael,

Donc dans mon dernier commit: 
https://github.com/bellisa03/tophit/commit/f4991d2902bf724f07f9ab93b7358791e19cf9dd

Tentatives infructueuses de faire fonctionner un jquery.
Est-ce qu'il me manque la référence d'un script?
Est-ce que je dois utiliser composer?

Je l'ai testé dans la vue suivante:
src/Template/Polls/edit.ctp
(J'ai essayé plusieurs fonctions différentes, plusieurs glyphicons...)

Il y a aussi des références de scripts dans le default bien sûr:
https://github.com/bellisa03/tophit/blob/master/src/Template/Layout/default.ctp

Voilà, ce serait cool si tu sais y jeter un oeil ;-)

:-*

**Comment by michael-lurquin** [comment]
Premier problème que je vois, c'est la classe utilisé pour le glyphicon, tu as mis :
```html
<span class="fa-calendar-o:before"></span>
```
Alors que cela devrait être :
```html
<span class="fa fa-calendar-o"></span>
```
Mais je pense qu'il te manque quelques fichiers pour afficher les glyphicons de Font-Awesome, moi j'en ai 6 alors que tu n'en as que 3, il y a déjà un problème. Sinon, ce que tu peux faire c'est inclure la CSS Font-Awesome directement depuis leurs serveurs (sans la télécharger et à mettre dans ton **Template/Layout/default.ctp**), comme ceci :

```html
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
```

Ensuite, tu as besoin de télécharger les librairies de DatimePicker, donc tu as besoin de rajouter ceci dans ton **Template/Layout/default.ctp** :

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
<script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
```

Si tu ne le fais pas, tu peux afficher les erreurs de Javascript dans la console, c-à-d sur Chrome (que je pense que tu as, sinon sur Firefox s'est pareil "Outils de développeurs" et puis tu as un onglet "Console" et c'est là qu'apparaîtrons toutes les erreurs JS) :

![image](https://cloud.githubusercontent.com/assets/7093602/21962750/e91919b6-db2d-11e6-8297-a1c09663f406.png)

Normalement pour le moment tu devrais avoir une erreur du style **datetimepicker() function undefined**, si tu inclus les librairies que je t'ai indiqué l'erreur disparaîtra.

**Comment by michael-lurquin** [comment]
Si tu as encore des problèmes, alors il me faudra un dump de ta base de données, car je ne sais pas accéder à la page dite sans identifiants et sans DB !

**Comment by bellisa03** [comment]
Cool! 
Merci, je vais déjà regarder à tout ça.
Pour le glyphicon, j'ai essayé plusieurs trucs qui n'ont pas fonctionnés... Mais bon, si il me manque déjà la bonne librairie à la base, ça risquait de toute façon pas de marcher ;-)

En tout cas, un tout grand merci pour ton aide, tu m'apprends déjà pas mal de trucs!
Je te tiens au courant, et je t'envoie un dump si jamais ! :-*

**Comment by bellisa03** [comment]
@michael-lurquin 
Alors...

J'ai dû mettre les scripts date picker et autres jquery au début de ma vue "default", parce que sinon il n'avait pas accès à l'info au moment voulu (pourtant, ils mettent exprès les scripts js en fin de template pour ne pas ralentir le chargement de la page... bref ;-) )...

J'arrive maintenant à avoir un datepicker... qui fonctionne pas super (il faudra que je regarde à la configuration des min et max date, et à faire fonctionner la sauvegarde en DB).
Mais bon, c'est déjà ça ;-) 

J'ai malgré tout un problème avec le font-awesome.
J'ai le message suivant sur la console:
![image](https://cloud.githubusercontent.com/assets/20112323/21964278/6ac5ee10-db49-11e6-9b04-4ed66ece267f.png)

J'ai essayé ton lien... ça n'a pas fonctionné. J'ai peut-être loupé un truc quelque part?
Pour les fichiers manquants, il y en a qui ne passe pas dans le github, je ne sais pas pourquoi... Voici un printscreen de mon arborescence avec les fichiers présents:
![image](https://cloud.githubusercontent.com/assets/20112323/21964385/30c53660-db4b-11e6-8145-14ec318a2210.png)

Je me demande si le souci n'est pas une question de version du fontawesome.
Quand tu télécharges le template sur gettemplate.com, tu as dans le fichier font-awesome.min.css
plusieurs références du genre (j'ai aussi testé en changeant le chemin en chemin absolu pour être sûre)
![image](https://cloud.githubusercontent.com/assets/20112323/21964432/545a8cd2-db4c-11e6-8dd9-d0fcae27b1b6.png)

Alors que dans le fichier fontawesome-webfont.eot, la référence est la suivante:
![image](https://cloud.githubusercontent.com/assets/20112323/21964449/829a7d8c-db4c-11e6-87c1-2e962e1d9927.png)
Donc, est-ce qu'il n'y a pas un souci avec d'un côté 4.0.2 d'un côté et du 4.0.3 de l'autre?

Bref, si tu as envie de tester avec la BD, voici un dump comme promis:

[tophit.zip](https://github.com/bellisa03/tophit/files/706746/tophit.zip)

Bizzzz et mille mercis d'avance :-)

**Comment by bellisa03** [comment]
voilà, je t'ai envoyé un dump.
Si tu as l'occasion c'est cool...
Mais si jamais pas de souci, j'embêterai les profs jeudi ;-)

Merci merci!
Bizzzz et bonne fin de week-end.

Ps: mot de passe de tous les users de la BD, je me suis pas cassé la tête :
test

2017-01-15 14:26 GMT+01:00 LURQUIN Michaël <notifications@github.com>:

**Comment by michael-lurquin** [comment]
Je ne sais pas pourquoi tu n'arrives pas à mettre sur GIT les fichiers du dossier **fonts** !

## Solution ##
Bref, le problème jQuery, c'est normal il faut que la librairie jQuery soit chargée avant tout appel jQuery et pour résoudre ton problème je te propose de faire une section **scripts** et **styles**, comme ceci :

Fichier **edit.ctp** :
```html
<?= $this->start('styles') ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css" rel="stylesheet">
<?= $this->end() ?>

<?= $this->start('scripts') ?>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript">
      $(document).ready(function () {
          $('#datetimepicker2').datetimepicker({
              locale: 'fr'
          });
      });
    </script>
<?= $this->end() ?>
```
Dans le fichier **default.ctp**, en dessous de la ligne qui injecte la librairie **Font-Awesome**, mettre :
```html
<?= $this->fetch('styles') ?>
```
Et tout à la fin de tes scripts mettre :
```html
<?= $this->fetch('scripts') ?>
```
Ainsi on va créé une section **scripts** et **styles** dans le template général et injecter du contenu dans ces sections depuis la page **edit.ctp**. De cette façon on injecte du CSS et JS uniquement pour les pages spéciales et non partout (comme on pourrai le faire mais alors soucis de performances) !

Pour les erreurs que tu as dans la console, c'est normal car il te manque des fichiers de fonts pour les Glyphicons (**attention** tu en charges 2, celles de Bootstrap et de FontAwesome).
* Pour Bootstrap, tu peux télécharger le bootstrap complet et récupérer le dossier **fonts** et y mettre les fichiers dans ton dossier **fonts**, à cette adresse : https://github.com/twbs/bootstrap/archive/v3.3.7.zip
* Pour FontAwesome, même chose à cette adresse : http://fontawesome.io/assets/font-awesome-4.7.0.zip

Il vaut mieux **toujours** récupérer les fichiers sur leurs site originaux que sur gettemplate.com. Mais si tu ne souhaites pas t'embêter avec tout ça, tu peux simplement utiliser les fichiers CSS de bootstrap et fontawesome directement depuis leurs serveurs (et ne pas les télécharger et utiliser localement) : 
* ```<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7">```
* ```<link rel=stylesheet" href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css">```

Une fois que tu auras télécharger ces fichiers-là et après les avoir mis au bon endroit, tu pourras bien sûr supprimer la ligne :

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
```

## Pour les erreurs de références ##

![image](https://cloud.githubusercontent.com/assets/7093602/21964795/44bea234-db53-11e6-9d62-cc437718910d.png)
Ce sont les **fonts** qui se trouve dans le dossier **fonts** qui **DOIT** être juste à côté du dossier **css** sinon ça ne fonctionne pas et bien sûr il faut qu'il y ait toutes les **fonts** de FontAwesome, qui se trouve dans le lien que je t'ai donné. En gros tu dois avoir une arborescence plus ou moins comme celle-ci (arborescence d'un autre de mes projets et donc qui ne doit pas réellement refléter la même chose chez toi, mais c'est le minimum que tu dois avoir) :
![image](https://cloud.githubusercontent.com/assets/7093602/21964872/4ea7db8e-db54-11e6-9e77-bf9987eb0b8c.png)

Si ça ne vas pas, je peux faire les modifications et tu mettre à jour simplement ton repo de ton côté.

**Comment by michael-lurquin** [comment]
J'allais oublier, la ligne pour l'icône du calendrier doit-être : 
```html
<span class="fa fa-calendar-o"></span>
```
Sinon, ça ne fonctionne pas ! Maintenant à toi choisir l'icône qu'il te convient, perso j'aurai pris l'icône sans le ```-o```, à toi de voir l'icône qui te convient depuis la liste officiel : http://fontawesome.io/icons/ (et tu tapes **calendar** dans la barre de recherche)

**Comment by michael-lurquin** [comment]
Et si tu souhaites avoir un input plus joli, comme ceci :
![image](https://cloud.githubusercontent.com/assets/7093602/21965090/b96f64d8-db58-11e6-88c1-d70504d2514c.png)
Tu dois faire :
```html
<div class="form-group">
    <?= $this->Form->label('begindate', 'Début')?>
    <div class='input-group date' id='datetimepicker2'>
        <?= $this->Form->input('begindate', ['type' => 'text', 'label' => false])?>
        <span class="input-group-addon">
            <span class="fa fa-calendar"></span>
        </span>
    </div>
</div>
```

**Comment by bellisa03** [comment]
@michael-lurquin 
Waouhh!!! 
Tu es ma lumière au bout du tunnel :-P ;-)
Je vais regarder à tout ça!!

Encore un TOUT grand merci!!
:-*

**Comment by bellisa03** [comment]
@michael-lurquin 
CA FONCTIONNE!! :-P
Merci!
:-*
